using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace Quiz_game_design_and_coded_solution
{
    public partial class General_knowledge_question : Form
    {
        // quiz game variables
        int correctAnswer;
        int questionNumber = 1;
        int optionnumber = 0;
        int score = 0;
        int percentage;
        int totalQuestions;
        DateTime startTime = DateTime.Now;
        int[] goArray;

        
        static string FilePath = @"D:\NEA TECHNICAL SOLUTION\9-02-2023---NEA-UPDATED-PROJECT-main\Quiz game design and coded solution\bin\Debug\gk.txt";
        List<string> questions;

        public General_knowledge_question()
        {
            question_reading(); // calls the question reading method
            InitializeComponent();// a method generated by Visual Studio that initializes all the components of the form
            askQuestion(0, 9);// 1 and 10 as arguments. This method likely retrieves and displays questions, with the arguments indicating the range of questions to retrieve (in this case, from the first to the 10th question).
            totalQuestions = 10; // this is the total amount of questions
            timer1.Start(); // start timer
        }

        public void question_reading() // public method for question_reading
        {
            FilePath = System.Environment.CurrentDirectory + "\\fad.txt";
            int count = 0; // this declares the count variable as an integer
            string data; // this declares the data as a string 
            FileStream fileStream = new FileStream(FilePath, FileMode.Open, FileAccess.Read);
            StreamReader streamReader = new StreamReader(fileStream);

            questions = new List<string>();// instantiates the list

            while (count < 60) // while count is less than 60
            {
                data = streamReader.ReadLine();
                questions.Add(data);
                count++;
            }

        }

        private void checkAnswereEvent(object sender, EventArgs e)
        {
            var senderObject = (Button)sender;


            int buttonTag = Convert.ToInt32(senderObject.Tag);
            if (buttonTag == correctAnswer)
            {
                score = score + 1;
                label2.Text = "Score: " + Convert.ToString(score);

            }
            optionnumber = 5;
            questionNumber += 1;
            askQuestion(questionNumber, optionnumber);

        
        }

        public void askQuestion(int qnum, int optionnumber)
        {

            pictureBox1.Image = Properties.Resources.images;



            try
            {
                label1.Text = questions[(qnum - 1) * (optionnumber + 1)]; // the question asked to the user
                string[] options = new string[] { questions[(qnum - 1) * (optionnumber + 1) + 1], questions[(qnum - 1) * (optionnumber + 1) + 2], questions[(qnum - 1) * (optionnumber + 1) + 3], questions[(qnum - 1) * (optionnumber + 1) + 4] };
                button1.Text = options[0];
                button2.Text = options[1];
                button3.Text = options[2];
                button4.Text = options[3];
                correctAnswer = Convert.ToInt32(questions[(qnum - 1) * (optionnumber + 1) + 5]);
                if (questionNumber == 10)
                {
                    timer1.Stop();

                    percentage = (int)Math.Round((double)(score * 100)) / totalQuestions;

                    MessageBox.Show("Quiz Ended!" + Environment.NewLine + "You have answered " + score + " questions correctly" + Environment.NewLine +
                    "Your total percentage is " + percentage + "%" + Environment.NewLine +
                    "Click OK to play again");
                    score = 0;
                    questionNumber = 0;

                    DateTime time = DateTime.Now;
                    string user = lblUserName.Text;
                    string SQL_2 = "INSERT INTO tblUserScores (UserName, TestDate, Score) VALUES '" + user + "','" + time + "','" + percentage + "');";
                    DBCon.AmendAddInsertData(SQL_2);

                }
            }
            catch (Exception ex) 
            { 
                MessageBox.Show(ex.Message);
            }



            

            




        }

        public void exitBtn_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        

        private void label2_Click(object sender, EventArgs e)
        {
            var senderObject = (Button)sender;
            int buttonTag = Convert.ToInt32(senderObject.Tag);

            if (buttonTag == correctAnswer) // selection. If the selected answer is equal to the correct answer the score will be incremented by one.
            {
                score = score + 1; // score will be incremented by one

                score = 0;
                int goscore = goArray[0];

                this.Hide();
                Form1 f1 = new Form1();
                f1.ShowDialog();
                this.Close();
            }
        }

        private void General_knowledge_question_Load(object sender, EventArgs e)
        {
            
            lblUserName.Text = System.Environment.UserName;
            
        }
        private void timer1_Tick(object sender, EventArgs e)
        {
            DateTime nowDateTime = DateTime.Now;
            var currentTime = Math.Abs(startTime.Second - nowDateTime.Second);
            lbltimer.Text = currentTime.ToString();
        }
    }
}

